export const EXPERIENCE = [
  {
    name: 'Porphyrio',
    from: '09/2019',
    to: '11/2019',
    technologies: [{ name: 'React' }, { name: 'TypeScript' }, { name: 'Node.js' }],
  },
  {
    name: 'ChatLayer',
    from: '04/2019',
    to: '06/2019',
    technologies: [{ name: 'React' }, { name: 'Node.js' }, { name: 'Docker' }],
  },
  {
    name: 'Neanex',
    from: '02/2018',
    to: '02/2019',
    children: [
      {
        name: 'Robovision 3D labeller',
        technologies: [
          { name: 'WebGL' },
          { name: 'ThreeJS' },
          { name: 'Vue' },
          { name: 'Node.js' },
        ],
      },
      {
        name: 'Neanex',
        technologies: [
          { name: 'WebGL' },
          { name: 'Node.js' },
          { name: 'Neo4J' },
          { name: 'Structr' },
          { name: 'React' },
          { name: 'Apollo GraphQL' },
        ],
      },
    ],
  },
  {
    name: 'SlickSS',
    from: '03/2017',
    to: '08/2017',
    children: [
      {
        name: 'SlickSS',
        technologies: [{ name: 'Docker' }, { name: 'CoffeScript' }, { name: 'ExtJS' }],
      },
    ],
  },
  {
    name: 'Freelance & Open Source Projects',
    from: '04/2015',
    to: '02/2016',
    children: [
      {
        name: 'Freelance & Open Source',
        technologies: [
          { name: 'ReactJS' },
          { name: 'AngularJS' },
          { name: 'JavaScript' },
          { name: 'Webpack' },
          { name: 'RollupJS' },
          { name: 'WebGL' },
          { name: 'WebAudio' },
        ],
      },
    ],
  },
  {
    name: '4C / Cronos',
    from: '11/1998',
    to: '03/2015',
    children: [
      {
        name: 'AGIV',
        technologies: [
          { name: 'OpenLayers' },
          { name: 'Node.js' },
          { name: 'JavaScript' },
          { name: 'CSS' },
          { name: 'HTML5' },
          { name: 'XML' },
          { name: 'JSON' },
          { name: 'Aptana Jaxer' },
          { name: 'Buddata Studio (JavaScript-based rich web client)' },
          { name: 'Buddata UI Framework (JavaScript codebase used by Buddata Studio)' },
          { name: 'Buddata OGC Web Feature Service 2.0' },
          { name: 'Enterprise Architect (Sparx)' },
          { name: 'ShapeChange 2.0' },
          { name: 'Buddata ebXML3.0 Registry Service' },
          { name: 'OGC CSW for ebRIM resolver-broker' },
          { name: 'Bizagi Process Modeler' },
          { name: 'MySQL' },
          { name: 'PostgreSQL/PostGIS' },
        ],
      },
      {
        name: 'Itineris',
        technologies: [
          { name: 'C#' },
          { name: 'MS Visual Studio' },
          { name: 'XSLT' },
          { name: 'MS Word templates' },
          { name: 'SQLServer' },
          { name: 'Microsoft AX' },
        ],
      },
      {
        name: 'Arcelor Mital Logistics',
        technologies: [{ name: 'C#' }, { name: 'XSLT' }, { name: 'SQL Server' }],
      },
      {
        name: 'kZenLabs',
        technologies: [
          { name: 'Java' },
          { name: 'C#' },
          { name: 'Node.js' },
          { name: 'Javascript' },
          { name: 'HTML5' },
          { name: 'CSS' },
          { name: 'XML' },
          { name: 'JSON' },
          { name: 'Aptana Jaxer' },
          { name: 'Buddata Studio' },
          { name: 'PostgreSQL / PostGIS' },
          { name: 'MySQL' },
        ],
      },
      {
        name: 'GENESIS FP7 - 4CT/kZenLabs',
        technologies: [
          { name: 'Java' },
          { name: 'C#' },
          { name: 'Node.js' },
          { name: 'Javascript' },
          { name: 'CSS' },
          { name: 'HTML5' },
          { name: 'XML' },
          { name: 'JSON' },
          { name: 'Apatan Jaxer' },
          { name: 'Buddata Studio (JavaScript-based rich web client)' },
          { name: 'Buddata UI Framework (JavaScript codebase used by Buddata Studio)' },
          { name: 'Buddata OGC Web Feature Service 2.0' },
          { name: 'Buddata OGC Web Processing Service' },
          { name: 'Buddata OGC CSW for ebRIM resolver-broker' },
          { name: 'PostgreSQL/PostGIS' },
          { name: 'MySQL' },
        ],
      },
    ],
  },
  { name: 'Business Solutions', from: '12/1997', to: '09/1998' },
  { name: 'Solvay NV', from: '05/1997', to: '11/1997' },
];
